import './globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
// import { ApolloWrapper } from '@/src/apollo/apollo-wrapper';

export const metadata: Metadata = {
	title: 'Canvas Notifier',
	description: 'Generated by create next app',
};

// app/layout.tsx

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
